---
# Some tasks for Sandstorm were taken from https://github.com/iflowfor8hours/sandcastle. Please visit this repo to see
# a complete playbook only for sandstorm.
- name: Create sandstorm group
  group:
    name: sandstorm
  become: yes

- name: Create sandstorm user
  user:
    name: sandstorm
    group: sandstorm
    createhome: no
    system: yes
  become: yes

- name: Fetch sandstorm installer
  get_url:
    url: https://install.sandstorm.io/
    dest: /tmp/sandstorm-installer.sh

- name: Create log folder for nginx
  become: yes
  file:
    dest: "/var/log/nginx/{{ sandstorm_hostname }}"
    state: directory

- name: chmod sandstorm installer
  file:
    name: /tmp/sandstorm-installer.sh
    mode: 755
  become: yes

- name: Run sandstorm installer
  command: /tmp/sandstorm-installer.sh -d -e creates=/opt/sandstorm
  become: yes

- name: Configure sandstorm
  become: yes
  template:
    src: tasks/install-sandstorm/templates/sandstorm.conf.j2
    dest: /opt/sandstorm/sandstorm.conf
  register: sandstorm_conf_updated

- name: Start the sandstorm service
  become: yes
  service:
    name: sandstorm
    state: restarted
  when: sandstorm_conf_updated.changed

- name: Copy new sandstorm nginx conf from template
  become: yes
  template: src=tasks/install-sandstorm/templates/sandstorm-nginx.conf.j2 dest=/etc/nginx/sites-available/sandstorm.conf
  notify:
    - restart nginx

- name: Create link of the sandstorm nginx conf
  become: yes
  file: src=/etc/nginx/sites-available/sandstorm.conf dest=/etc/nginx/sites-enabled/sandstorm.conf state=link
  notify:
    - restart nginx

