version: '2'

volumes:
  nextcloud:
  nextclouddb:
  onlyoffice_postgresql_data:
 
networks:
  nextcloud:
    driver: "bridge" 

services:
  nextcloud-mariadb:
    container_name: nextcloud-mysql
    image: mariadb
    restart: always
    volumes:
      - nextclouddb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD={{nextcloud_mysql_root_password}}
      - MYSQL_PASSWORD={{nextcloud_mysql_user_password}}
      - MYSQL_DATABASE={{nextcloud_mysql_database}}
      - MYSQL_USER={{nextcloud_mysql_database_user}}
    networks:
      - nextcloud

  nextcloud-app:  
    image: nextcloud
    container_name: nextcloud-app
    volumes:
       - nextcloud:/var/www/html
       - "{{services_folder}}/nextcloud/data:/var/www/html/data"
    restart: always
    depends_on:
      - nextcloud-mariadb
    expose:
      - '80'
    networks:
      - nextcloud

  onlyoffice-documentserver:
    image: onlyoffice/documentserver:latest
    container_name: onlyoffice-documentserver
    depends_on:
      - onlyoffice-postgresql
      - onlyoffice-redis
      - onlyoffice-rabbitmq
    environment:
      - POSTGRESQL_SERVER_HOST=onlyoffice-postgresql
      - POSTGRESQL_SERVER_PORT=5432
      - POSTGRESQL_SERVER_DB_NAME={{nextcloud_onlyoffice_postgresql_database}}
      - POSTGRESQL_SERVER_USER={{nextcloud_onlyoffice_postgresql_database_user}}
      - RABBITMQ_SERVER_URL=amqp://guest:guest@onlyoffice-rabbitmq
      - REDIS_SERVER_HOST=onlyoffice-redis
      - REDIS_SERVER_PORT=6379
      - EXCLUDE_PORTS=443
      - HTTP_CHECK=GET /healthcheck
      - EXTRA_SETTINGS=http-check expect string true
      # Uncomment the string below to redirect HTTP request to HTTPS request.
      #- FORCE_SSL=true
    stdin_open: true
    restart: always
    expose:
      - '80'
    networks:
      - nextcloud

  onlyoffice-redis:
    container_name: onlyoffice-redis
    image: redis
    restart: always
    expose:
      - '6379'
    networks:
      - nextcloud

  onlyoffice-rabbitmq:
    container_name: onlyoffice-rabbitmq
    image: rabbitmq
    restart: always
    expose:
      - '5672'
    networks:
      - nextcloud

  onlyoffice-postgresql:
    container_name: onlyoffice-postgresql
    image: postgres:9.5
    environment:
      - POSTGRES_DB={{nextcloud_onlyoffice_postgresql_database}}
      - POSTGRES_USER={{nextcloud_onlyoffice_postgresql_database_user}}
    restart: always
    expose:
      - '5432'
    volumes:
      - onlyoffice_postgresql_data:/var/lib/postgresql
    networks:
      - nextcloud

