---
#- name: Create new ssl certificate
#  shell: letsencrypt certonly --agree-tos --email {{ letsencrypt_email }} --keep-until-expiring -n --standalone --standalone-supported-challenges tls-sni-01 -d {{ redmine_domain }}
#  become: yes
#  when: enable_letsencrypt
#
#- name: Create folder for redmine files, theme and plugins on host
#  become: yes
#  file: path={{ item }} state=directory owner=www-data group=www-data
#  with_items:
#    - "/var/redmine-{{redmine_name}}"
#    - "/var/redmine-{{redmine_name}}/themes"
#    - "/var/redmine-{{redmine_name}}/files"
#    - "/var/redmine-{{redmine_name}}/plugins"
#    - "/var/redmine-{{redmine_name}}/database"
#
#- name: Create docker compose file from template
#  become: yes
#  template: src=tasks/install-redmine/templates/redmine-compose.yml dest=/var/redmine-{{redmine_name}}/docker-compose.yml owner={{ansible_env.USER}}
#
#- name: Start docker redmine and mysql server
#  shell: docker-compose up -d chdir=/var/redmine-{{redmine_name}} creates=/tmp/started-redmine-docker-compose
#
#- name: Copy new nginx conf from template
#  become: yes
#  template: src=tasks/install-redmine/templates/redmine.conf dest=/etc/nginx/sites-available/redmine-konekto.conf
#  notify:
#    - restart nginx
#
#- name: Create link of nginx conf
#  become: yes
#  file: src=/etc/nginx/sites-available/redmine-konekto.conf dest=/etc/nginx/sites-enabled/redmine-konekto.conf state=link
#  notify:
#    - restart nginx

- name : Create backup script from template file
  become: yes
  template:
    src: tasks/install-redmine/templates/backup.sh
    dest: "/var/redmine-{{redmine_name}}/backup.sh"
    mode: "0744"
    owner: "{{ansible_user}}"

- name: Create crontab for backup script
  cron:
    name: "{{redmine_name}}-backup-script"
    minute: "0"
    hour:  "3"
    job: "/var/redmine-{{redmine_name}}/backup.sh"
    user: "{{ansible_user}}"

- name: Create redmine backup folder
  file:
    state: directory
    owner: "{{ansible_user}}"
    mode: "0774"
    path: "{{GLOBAL_BACKUP_FOLDER}}/{{redmine_name}}-redmine"